[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tuckercnn"
version = "0.0.1"
dynamic = ["dependencies"]

[tool.setuptools]
packages = ["tuckercnn"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}