# -----------------------------------------------------------
# NNUNET TRAINING SETUP
# -----------------------------------------------------------
# dataset_id: '300'
# pretrained_weights: None
#dataset_id: '001'
#pretrained_weights: '/data/core-rad/data/tucker/results/Dataset291_TotalSegmentator_part1_organs_1559subj/nnUNetTrainerNoMirroring__nnUNetPlans__3d_fullres/fold_0/checkpoint_final.pth'
dataset_id : '006'
pretrained_weights: '/data/core-rad/data/tucker/results/Dataset297_TotalSegmentator_total_3mm_1559subj/nnUNetTrainer_4000epochs_NoMirroring__nnUNetPlans__3d_fullres/fold_0/checkpoint_final.pth'

epochs: 100
learning_rate: 0.0001
optimizer: adam

# -----------------------------------------------------------
# TUCKER CONFIG
# -----------------------------------------------------------
tucker_config:
    tucker_args:
        rank_mode: relative
        rank_factor: 0.3
        rank_min: 8
        decompose: True
        verbose: True
    apply_tucker: True
    inference_bs: 1
    ckpt_path: checkpoints/tucker_test.pt
    save_model: True
    load_model: False

