# -----------------------------------------------------------
# NNUNET TRAINING SETUP
# -----------------------------------------------------------
dataset_id: <your dataset id>
pretrained_weights: <path to pretrained weights>

epochs: 50
learning_rate: 0.00001
optimizer: adam

# -----------------------------------------------------------
# TUCKER CONFIG
# -----------------------------------------------------------
tucker_config:
    tucker_args:
        rank_mode: relative
        rank_factor: 0.3
        rank_min: 8
        decompose: True
        verbose: True
    apply_tucker: True
    inference_bs: 1
    ckpt_path: checkpoints/tucker_test.pt
    save_model: True
    load_model: False

