# -----------------------------------------------------------
# PATHS
# -----------------------------------------------------------
out_root: /data/core-rad/data/tucker_predictions
out_id: dummy_run

label_root: /data/core-rad/data/tucker/raw/000-tdata/labelsTs
metric_csv_path: results/inference_test.csv
eval_workers: 32

# -----------------------------------------------------------
# TUCKER CONFIG
# -----------------------------------------------------------
fast_model: True
tucker_config:
    tucker_args:
        rank_mode: relative
        rank_factor: 0.3
        rank_min: 16
        decompose: True
        verbose: True
    apply_tucker: False
    inference_bs: 1
    ckpt_path:
    save_model: False
    load_model: False
