# -----------------------------------------------------------
# PATHS
# -----------------------------------------------------------
out_root: /data/core-rad/data/tucker_predictions
out_id: test_run

# -----------------------------------------------------------
# TUCKER CONFIG
# -----------------------------------------------------------
fast_model: True
tucker_config:
    tucker_args:
        rank_mode: relative
        rank_factor: 0.3
        rank_min: 16
        decompose: True
        verbose: True
    apply_tucker: True
    inference_bs: 1
    ckpt_path:
    save_model: False
    load_model: False
