dataset_id: '006'
epochs: 50
learning_rate: 0.0001
optimizer: adam
pretrained_weights: /data/core-rad/data/tucker/results/Dataset297_TotalSegmentator_total_3mm_1559subj/nnUNetTrainerNoMirroring__nnUNetPlans__3d_fullres/fold_0/checkpoint_final.pth
tucker_config:
  apply_tucker: true
  ckpt_path: checkpoints_finetune/05_fast.pt
  inference_bs: 1
  load_model: false
  save_model: true
  tucker_args:
    decompose: true
    rank_factor: 0.3
    rank_min: 8
    rank_mode: relative
    verbose: true
